---
title: Jungleskipper
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Daniel Saxil-Nielsen
baseurl: http://jungleskipper.com
google_analytics: UA-37892446-1
