---

timezone: UTC

collections:
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: ''

title: Jungle Skipper
description: Bringing you reviews, news and facts from Disney theme parks around the world.

twitter:
  username: _jungleskipper
facebook:
  publisher: 105751913458455

social:
  name: Jungle Skipper
  links:
    - https://twitter.com/_jungleskipper
    - https://www.facebook.com/thejungleskipper
    - https://instagram.com/_jungleskipper
    
lang: en_UK
  

authorTwitter: _jungleskipper
author: Daniel Saxil-Nielsen
url: https://jungleskipper.com
baseurl: ''
paginate: 5

gems:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

permalink: "/:categories/:title"
sass:
  sass_dir: _sass
