---
title: Jungle Skipper
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
  category:
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: ''
- scope:
    path: ''
    type: category
  values:
    layout: category
author: Jungle Skipper
description: Reviews, news and facts from Disney parks around the world.
url: https://jungleskipper.com
twitter:
  username: _jungleskipper
facebook:
  publisher: 105751913458455
social:
  name: Jungle Skipper
  links:
  - https://twitter.com/_jungleskipper
  - https://www.facebook.com/thejungleskipper
  - https://instagram.com/_jungleskipper
lang: en_UK
baseurl: ''
paginate: 5
gems:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
permalink: "/:categories/:title"
sass:
  sass_dir: _sass
emptyArray: []
