---
title: Jungleskipper
author: Daniel Saxil-Nielsen
baseurl: 'http://jungleskipper.com'
google_analytics: 'UA-37892446-1'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
